apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compute-worker
  template:
    metadata:
      labels:
        app: compute-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: karpenter.k8s.gcp/instance-family
                    operator: In
                    values: ["c2", "c2d"]
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          name: compute-worker
          resources:
            requests:
              cpu: "1"
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
