#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

GENERATED_HEADER="<!-- This file is generated by hack/docs-generate.sh. Do not edit manually. -->"

generate() {
  local source=$1 config=$2 output=$3
  crd-ref-docs \
    --source-path="${source}" \
    --config="${config}" \
    --renderer=markdown \
    --output-path="${output}" \
    --max-depth=10
  # Remove cross-references to ignored *List types and any resulting empty
  # "_Appears in:_" headers (crd-ref-docs emits these even for ignored types).
  python3 - "${output}" <<'EOF'
import re, sys
path = sys.argv[1]
content = open(path).read()
# Drop entire sections for *List types (#### SomeList ... up to next ####)
content = re.sub(r'#### \w+List\n.*?(?=\n#### |\Z)', '', content, flags=re.DOTALL)
# Drop "- [SomeList](#somelist)" cross-reference lines
content = re.sub(r'^- \[[^\]]*List\]\(#[^)]+\)\n', '', content, flags=re.MULTILINE)
# Drop "_Appears in:_" headers left with no following list items
content = re.sub(r'_Appears in:_\n(?=\n|##)', '', content)
open(path, 'w').write(content)
EOF
  # Prepend the generated-file header
  printf '%s\n' "${GENERATED_HEADER}" | cat - "${output}" > "${output}.tmp"
  mv "${output}.tmp" "${output}"
}

echo "Generating GCENodeClass reference docs..."
generate \
  "${REPO_ROOT}/pkg/apis/v1alpha1" \
  "${REPO_ROOT}/hack/crd-ref-docs/gcenodeclass.yaml" \
  "${REPO_ROOT}/docs/reference/gcenodeclass.md"

echo "Generating NodePool reference docs..."
generate \
  "${REPO_ROOT}/vendor/sigs.k8s.io/karpenter/pkg/apis/v1" \
  "${REPO_ROOT}/hack/crd-ref-docs/nodepool.yaml" \
  "${REPO_ROOT}/docs/reference/nodepool.md"

echo "Done."
