apiVersion: v1
entries:
  karpenter:
  - apiVersion: v2
    appVersion: v0.2.1
    created: "2026-03-13T10:26:31.822558+01:00"
    description: A Helm chart for Kubernetes
    digest: 6e5b0710f6a203ecf850940402a608fbefae742f7956b35e6f3c64a1ecb0645e
    name: karpenter
    type: application
    urls:
    - karpenter-v0.2.1.tgz
    version: v0.2.1
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2026-03-13T10:26:31.821966+01:00"
    description: A Helm chart for Kubernetes
    digest: 673f10355ae62234bc554135a864924bbe81923af4a2f6b35caabffe7a709d6b
    name: karpenter
    type: application
    urls:
    - karpenter-v0.2.0.tgz
    version: v0.2.0
  - apiVersion: v2
    appVersion: v0.1.0
    created: "2026-03-13T10:26:31.821362+01:00"
    description: A Helm chart for Kubernetes
    digest: 00fc7da22fbd7b6fbf48dacb686efcdb3967b34a8076b3558f30177176749c89
    name: karpenter
    type: application
    urls:
    - karpenter-v0.1.0.tgz
    version: v0.1.0
  - apiVersion: v2
    appVersion: v0.1.0-rc.0
    created: "2026-03-13T10:26:31.820546+01:00"
    description: A Helm chart for Kubernetes
    digest: 6e89a07b4688dfed0d43c81d0ee92e54e9f9d6ef4c8ea5c2acd503521a6dda46
    name: karpenter
    type: application
    urls:
    - karpenter-v0.1.0-rc.0.tgz
    version: v0.1.0-rc.0
generated: "2026-03-13T10:26:31.818996+01:00"
