{{- if and .Values.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "karpenter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "karpenter.selectorLabels" . | nindent 6 }}
  {{- if not (eq .Values.serviceMonitor.sampleLimit nil) }}
  sampleLimit: {{ .Values.serviceMonitor.sampleLimit }}
  {{- end }}
  endpoints:
    - port: http-metrics
      path: /metrics
      {{- if and .Values.serviceMonitor.relabelings (not (hasKey .Values.serviceMonitor.endpointConfig "relabelings")) }}
      relabelings:
        {{- toYaml .Values.serviceMonitor.relabelings | nindent 6 }}
      {{- end }}
      {{- if and .Values.serviceMonitor.metricRelabelings (not (hasKey .Values.serviceMonitor.endpointConfig "metricRelabelings")) }}
      metricRelabelings:
        {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 6 }}
      {{- end }}
    {{- with .Values.serviceMonitor.endpointConfig }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end -}}
