apiVersion: karpenter.k8s.gcp/v1alpha1
kind: GCENodeClass
metadata:
  name: default-ubuntu
spec:
  serviceAccount: "" # fill me
  imageSelectorTerms:
    - family: Ubuntu2404
      version: v20250106
    # - family: Ubuntu2404
    #   channel: cluster
  labels:
    env: dev
  networkTags:
    - karpenter-ubuntu
  disks:
    - category: pd-balanced
      sizeGiB: 60
      boot: true
