name: Docs

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
  pull_request:
    paths:
      - "docs/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install mdox
        run: go install github.com/bwplotka/mdox@latest

      - name: Lint markdown
        run: make docs-lint
