name: Verify

on:
  push:
    branches: [ "main" ]
  pull_request: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum
            hack/tools/go.sum

      - name: Install toolchain
        run: make toolchain

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.12.2
          only-new-issues: true

      - name: Verify
        run: make ci
