name: Pre-submit check

on:
  push:
    branches: [ "main" ]
  pull_request: {}

permissions:
  contents: read
  pull-requests: read

jobs:
  presubmit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Cache toolchain binaries
        uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: toolchain-${{ runner.os }}-${{ hashFiles('hack/toolchain.sh') }}

      - name: Install toolchain
        run: |
          make toolchain

      - name: Presubmit check
        run: |
          make presubmit

      - name: Lint Helm chart
        run: |
          make chart-lint
